name: Build and Analyze

on:
  push:
    branches:
      - master # ou main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # A versão do Python do seu projeto (ex: '3.9', '3.10', '3.11')

      # Não instalamos nenhuma dependência de teste ou mesmo o Faker em si.
      # Apenas garantimos que o pip esteja atualizado.
      - name: Install minimal dependencies for SonarScanner
        run: |
          python -m pip install --upgrade pip

      # Executar o SonarCloud Scan
      # Ele vai analisar os arquivos .py sem rodar testes ou coletar cobertura.
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}