name: Build and Analyze

on:
  push:
    branches:
      - master # ou main, dependendo do nome da sua branch principal
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a versão do Python que seu projeto usa (ex: '3.9', '3.10', '3.11')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Se seu projeto tiver um requirements.txt
          pip install pytest coverage # Instale pytest e coverage para testes e cobertura

      # Primeiro, rode os testes e colete a cobertura
      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest # Ou o comando para rodar seus testes (ex: python -m unittest discover)
          coverage xml -o coverage.xml # Gera o relatório no formato XML

      # Depois, execute o SonarCloud Scan para enviar a análise (incluindo a cobertura)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Seu token de segurança do SonarCloud