name: Build and Analyze

on:
  push:
    branches:
      - master # ou main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a versão do Python do seu projeto (ex: '3.9', '3.10', '3.11')

      # Instale apenas as dependências mínimas para o SonarScanner se o Faker não tiver um requirements.txt
      # e você não precisa de pytest/coverage para esta análise simplificada.
      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          # Nenhuma outra instalação pip aqui se você não precisa de testes/cobertura agora.

      # Executar o SonarCloud Scan (sem se preocupar com testes ou cobertura por enquanto)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}