name: Build and Analyze

on:
  push:
    branches:
      - master # ou main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # A versão do Python do seu projeto

      # PASSO COMBINADO: Instalar dependências, Faker, rodar testes e coletar cobertura
      - name: Install, Test, and Collect Coverage for SonarCloud
        run: |
          # 1. Instalar ferramentas básicas
          python -m pip install --upgrade pip
          pip install pytest coverage

          # 2. Instalar o próprio Faker no ambiente de teste
          #    Isso permite que os testes importem e executem o código do Faker.
          pip install -e .

          # 3. Rodar os testes com cobertura
          #    É crucial especificar o caminho para a pasta 'tests' do Faker.
          coverage run -m pytest tests/

          # 4. Gerar o relatório de cobertura no formato XML
          coverage xml -o coverage.xml

      # Passo crucial para executar o SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}